#!/usr/bin/env bash
# Regenerates the auto-generated sections of CLAUDE.md from the real filesystem.
# Hand-written sections (build, conventions) are left untouched.
# Triggered by the SessionStart hook; safe to run manually any time.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

CLAUDE_MD="CLAUDE.md"
START="<!-- AUTOGEN:START — regenerated by Scripts/update_claude_md.sh, do not edit by hand -->"
END="<!-- AUTOGEN:END -->"

[ -f "$CLAUDE_MD" ] || { echo "no CLAUDE.md, skipping"; exit 0; }

gen="$(mktemp)"
{
  echo "$START"
  echo

  echo "## Layout (\`Krokva/\`) — auto-generated"
  # Top-level dirs under Krokva/ (skip Resources noise)
  for d in $(find Krokva -mindepth 1 -maxdepth 1 -type d ! -name 'Resources' | sort); do
    echo "- \`${d#Krokva/}/\`"
  done

  echo
  echo "**Features** (\`Krokva/Features/\`):"
  feats="$(find Krokva/Features -mindepth 1 -maxdepth 1 -type d -exec basename {} \; 2>/dev/null | sort | paste -sd',' - | sed 's/,/, /g')"
  echo "${feats:-_none_}"

  echo
  echo "**Report cards** (\`Krokva/Features/Report/Cards/\`):"
  cards="$(find Krokva/Features/Report/Cards -maxdepth 1 -name '*.swift' -exec basename {} .swift \; 2>/dev/null | sort | paste -sd',' - | sed 's/,/, /g')"
  echo "${cards:-_none_}"

  echo
  echo "**City providers** (\`Krokva/Cities/Providers/\`):"
  provs="$(find Krokva/Cities/Providers -maxdepth 1 -name '*.swift' -exec basename {} .swift \; 2>/dev/null | sort | paste -sd',' - | sed 's/,/, /g')"
  echo "${provs:-_none_}"

  echo
  echo "## Persistent memory (read on demand)"
  MEM="$HOME/.claude/projects/-Users-mickhailovjack-Documents-Krokva/memory"
  if [ -d "$MEM" ]; then
    for f in "$MEM"/*.md; do
      base="$(basename "$f")"
      [ "$base" = "MEMORY.md" ] && continue
      # first non-frontmatter description line
      desc="$(awk -F': ' '/^description:/ {print $2; exit}' "$f")"
      echo "- \`memory/$base\` — ${desc:-}"
    done
  else
    echo "_memory dir not found_"
  fi

  echo
  echo "$END"
} > "$gen"

# Splice: replace existing AUTOGEN block, or append if markers absent.
if grep -qF "$START" "$CLAUDE_MD"; then
  awk -v start="$START" -v end="$END" -v genfile="$gen" '
    $0 ~ start {print; while ((getline line < genfile) > 0) if (line != start && line != end) print line; skip=1; next}
    $0 ~ end {print; skip=0; next}
    !skip {print}
  ' "$CLAUDE_MD" > "$CLAUDE_MD.tmp" && mv "$CLAUDE_MD.tmp" "$CLAUDE_MD"
else
  { echo; cat "$gen"; } >> "$CLAUDE_MD"
fi

rm -f "$gen"
echo "CLAUDE.md auto-sections refreshed."
